FROM 
   OFFERINGS 
   LEFT OUTER JOIN ISSUERS ON (OFFERINGS.ACCESSIONNUMBER = ISSUERS.ACCESSIONNUMBER) 
   LEFT OUTER JOIN RECIPIENTS ON (OFFERINGS.ACCESSIONNUMBER = RECIPIENTS.ACCESSIONNUMBER)
SELECT
  SALE_DATE as offering_saledate, 
  INDUSTRYGROUPTYPE as offering_IndustryGroupType,
  INVESTMENTFUNDTYPE as offering_InvestmentFundType, 
  ISSUERS.ENTITYNAME as issuer_EntityName, 
  RECIPIENTS.RECIPIENTNAME as recipient_name,
   CAST(
    CASE 
      WHEN TOTALOFFERINGAMOUNT == 'Indefinite' THEN 0
      ELSE TOTALOFFERINGAMOUNT 
     END
    AS BIGINT) AS TotalOfferingAmount
WHERE SALE_DATE BETWEEN DATE '2008-01-01' AND current_date()  