SELECT
   SALE_DATE, 
   INDUSTRYGROUPTYPE,
  INVESTMENTFUNDTYPE, ENTITYNAME,
   CAST(
    CASE 
      WHEN TOTALOFFERINGAMOUNT == 'Indefinite' THEN 0
      ELSE TOTALOFFERINGAMOUNT 
     END
    AS BIGINT) AS TOTALOFFERINGAMOUNT 
FROM 
OFFERINGS, ISSUERS 
WHERE OFFERINGS.ACCESSIONNUMBER = ISSUERS.ACCESSIONNUMBER   
AND 
SALE_DATE BETWEEN DATE '2008-01-01' AND current_date()